<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite errors="0" failures="2" hostname="TwistFatedeMac-mini.local" name="pytest" skipped="0" tests="2" time="0.067" timestamp="2020-03-05T20:04:20.414233">
        <testcase
            CPU="50%"
            MEM="450MB"
            classname="test_s"
            file="test_s.py"
            line="3"
            name="test_failed"
            time="0.001">
            <failure message="assert False">record_xml_attribute = &lt;bound method _NodeReporter.add_attribute of &lt;_pytest.junitxml._NodeReporter object at 0x101862580&gt;&gt;
    def test_failed(record_xml_attribute):
        record_xml_attribute(&quot;CPU&quot;,&quot;50%&quot;)
        record_xml_attribute(&quot;MEM&quot;, &quot;450MB&quot;)
&gt;       assert False
E       assert False

test_s.py:7: AssertionError</failure>
        </testcase>

        <testcase
            CPU="60%"
            MEM="200MB"
            classname="test_s"
            file="test_s.py"
            line="8"
            name="test_failed2"
            time="0.001">
            <failure message="assert False">record_xml_attribute = &lt;bound method _NodeReporter.add_attribute of &lt;_pytest.junitxml._NodeReporter object at 0x101862700&gt;&gt;

    def test_failed2(record_xml_attribute):
        record_xml_attribute(&quot;CPU&quot;, &quot;60%&quot;)
        record_xml_attribute(&quot;MEM&quot;, &quot;200MB&quot;)
&gt;       assert False
E       assert False

test_s.py:12: AssertionError
        </failure>
    </testcase>
</testsuite>
</testsuites>