{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\nUsers/tf/Desktop/PycharmProject/Pytest/Demo/TestCase/profile/test_sample3.py:10: AssertionError"}, "start": 1583221463422, "stop": 1583221463423, "uuid": "ad905d6e-85b0-4d1e-b6d5-ae834c60576a", "historyId": "bf064c956bd212c8090ee1080c3e9465", "testCaseId": "7532bbfc0214e8df8bdc699f58c5e143", "fullName": "TestCase.profile.test_sample3#test_answer", "labels": [{"name": "parentSuite", "value": "TestCase.profile"}, {"name": "suite", "value": "test_sample3"}, {"name": "host", "value": "TwistFatedeMac-mini.local"}, {"name": "thread", "value": "1286-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.profile.test_sample3"}]}