{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\nUsers/tf/Desktop/PycharmProject/Pytest/Demo/test_sample.py:10: AssertionError"}, "start": 1583221463358, "stop": 1583221463359, "uuid": "f08cda3d-6694-48de-94ce-a5be31660046", "historyId": "8954356b65e225b68bb20377189588a1", "testCaseId": "c398165193b396d834e5e030605bc655", "fullName": "test_sample#test_answer", "labels": [{"name": "suite", "value": "test_sample"}, {"name": "host", "value": "TwistFatedeMac-mini.local"}, {"name": "thread", "value": "1286-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_sample"}]}