{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\nUsers/tf/Desktop/PycharmProject/Pytest/Demo/TestCase/profile/test_sample2.py:10: AssertionError"}, "start": 1583221463417, "stop": 1583221463418, "uuid": "133223bd-dc1b-400f-83e3-17289260efdf", "historyId": "cbd18195d42f1b5c1278e75a721f16fa", "testCaseId": "a45948f1d1b4546b87f6230aefeca7f6", "fullName": "TestCase.profile.test_sample2#test_answer", "labels": [{"name": "parentSuite", "value": "TestCase.profile"}, {"name": "suite", "value": "test_sample2"}, {"name": "host", "value": "TwistFatedeMac-mini.local"}, {"name": "thread", "value": "1286-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.profile.test_sample2"}]}