{"name": "test_answer", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 5\n +  where 4 = func(3)", "trace": "def test_answer():\n>       assert func(3) == 5\nE       assert 4 == 5\nE        +  where 4 = func(3)\n\nUsers/tf/Desktop/PycharmProject/Pytest/Demo/TestCase/stress/test_sample.py:10: AssertionError"}, "start": 1583221463428, "stop": 1583221463428, "uuid": "bc34e137-a12f-4117-83fa-80148dbcc3da", "historyId": "8d7a46fda17a6bf7907b8f26206a93e5", "testCaseId": "f3233dc14870b3c39883c3e480e2b092", "fullName": "TestCase.stress.test_sample#test_answer", "labels": [{"name": "parentSuite", "value": "TestCase.stress"}, {"name": "suite", "value": "test_sample"}, {"name": "host", "value": "TwistFatedeMac-mini.local"}, {"name": "thread", "value": "1286-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCase.stress.test_sample"}]}